<?

/*
		Google-Translaste-Englische Sprachanpassung fuer Hacking-Demos:			
 */
      
$sprachtest  = "<p>\n This paragraph is the only text that is changed by the value for the language preference. If the parameter <code>sprache</code> is missing or set to an invalid value by a test, only this paragraph gets lost. The rest of the demo application works independently from the value of <code>sprache</code>. \n</p>\n";

$text_start  = "<p>\n This script is pretty much limited: All entries can be displayed as a list of titles, and individual entries can be completely reissued. In addition, visitors can register here as a user and registered users log in. \n</p>\n";

?>