<?

/*
		Sprachanpassung deutsch fuer Hacking-Demos:		
 */

$sprachtest  = "<p>\nDieser Absatz ist der einzige Text, der &uuml;ber die Sprachanpassung ge&auml;ndert wird. Wenn der Parameter <code>sprache</code> durch einen Test auf einen ung&uuml;tigen Wert gesetzt wird oder fehlt, fehlt nur dieser Absatz. Der Rest der Demo-Anwendung funktioniert unabh&auml;ngig vom Wert des Parameters <code>sprache</code>. \n</p>\n";

$text_start  = "<p>\nDieses Skript ist ziemlich beschr&auml;nkt: Es k&ouml;nnen alle Eintr&auml;ge als Titelliste angezeigt werden, und einzelne Eintr&auml;ge k&ouml;nnen komplett wieder ausgeben werden.  Au&szlig;erdem k&ouml;nnen sich die Besucher hier als Benutzer registrieren und registrierte Benutzer sich einloggen. \n</p>\n";

?>