<?php

/*
     Konfigurationsdatei fuer Hacking-Demo Beta

 */
define ("USERNAME", "root");
define ("PASSWORD", "");
define ("HOSTNAME", "localhost");
define ("DATENBANK", "hackdemodb");

/*
Default-Spracheinstellung - Moegliche Werte: de oder en
*/
define ("DEFAULTSPRACHE","de");

/*
Vollstaendiger Pfad zum Avatarverzeichnis /app/beta/avatare/
*/
define ("AVATARPFAD","/var/www/app/beta/avatare/");


?>